# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dynamo_pb2 as dynamo__pb2


class DynamoInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/dynamo.DynamoInterface/Put',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/dynamo.DynamoInterface/Get',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/dynamo.DynamoInterface/Read',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.ReadResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/dynamo.DynamoInterface/Heartbeat',
                request_serializer=dynamo__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=dynamo__pb2.HeartbeatRequest.FromString,
                )
        self.Replicate = channel.unary_unary(
                '/dynamo.DynamoInterface/Replicate',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.ReplicateResponse.FromString,
                )
        self.TransferData = channel.unary_unary(
                '/dynamo.DynamoInterface/TransferData',
                request_serializer=dynamo__pb2.DataBunchRequest.SerializeToString,
                response_deserializer=dynamo__pb2.DataBunchResponse.FromString,
                )
        self.PrintMemory = channel.unary_unary(
                '/dynamo.DynamoInterface/PrintMemory',
                request_serializer=dynamo__pb2.NoParams.SerializeToString,
                response_deserializer=dynamo__pb2.MemResponse.FromString,
                )
        self.Fail = channel.unary_unary(
                '/dynamo.DynamoInterface/Fail',
                request_serializer=dynamo__pb2.FailRequest.SerializeToString,
                response_deserializer=dynamo__pb2.FailRequest.FromString,
                )
        self.Gossip = channel.unary_unary(
                '/dynamo.DynamoInterface/Gossip',
                request_serializer=dynamo__pb2.NoParams.SerializeToString,
                response_deserializer=dynamo__pb2.NoParams.FromString,
                )
        self.PutStreaming = channel.stream_stream(
                '/dynamo.DynamoInterface/PutStreaming',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutResponse.FromString,
                )
        self.GetStreaming = channel.stream_stream(
                '/dynamo.DynamoInterface/GetStreaming',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetResponse.FromString,
                )


class DynamoInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintMemory(self, request, context):
        """debuggin functions

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamoInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.ReadResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dynamo__pb2.HeartbeatRequest.FromString,
                    response_serializer=dynamo__pb2.HeartbeatRequest.SerializeToString,
            ),
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.ReplicateResponse.SerializeToString,
            ),
            'TransferData': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferData,
                    request_deserializer=dynamo__pb2.DataBunchRequest.FromString,
                    response_serializer=dynamo__pb2.DataBunchResponse.SerializeToString,
            ),
            'PrintMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintMemory,
                    request_deserializer=dynamo__pb2.NoParams.FromString,
                    response_serializer=dynamo__pb2.MemResponse.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=dynamo__pb2.FailRequest.FromString,
                    response_serializer=dynamo__pb2.FailRequest.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=dynamo__pb2.NoParams.FromString,
                    response_serializer=dynamo__pb2.NoParams.SerializeToString,
            ),
            'PutStreaming': grpc.stream_stream_rpc_method_handler(
                    servicer.PutStreaming,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutResponse.SerializeToString,
            ),
            'GetStreaming': grpc.stream_stream_rpc_method_handler(
                    servicer.GetStreaming,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.DynamoInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DynamoInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Put',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Get',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Read',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Heartbeat',
            dynamo__pb2.HeartbeatRequest.SerializeToString,
            dynamo__pb2.HeartbeatRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Replicate',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.ReplicateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/TransferData',
            dynamo__pb2.DataBunchRequest.SerializeToString,
            dynamo__pb2.DataBunchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrintMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/PrintMemory',
            dynamo__pb2.NoParams.SerializeToString,
            dynamo__pb2.MemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Fail',
            dynamo__pb2.FailRequest.SerializeToString,
            dynamo__pb2.FailRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dynamo.DynamoInterface/Gossip',
            dynamo__pb2.NoParams.SerializeToString,
            dynamo__pb2.NoParams.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/dynamo.DynamoInterface/PutStreaming',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/dynamo.DynamoInterface/GetStreaming',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
